### ISSUE TITLE
Export 3D representation to OBJ-file

### ISSUE THREAD

**Issue by han16nah** [openalea/plantscan3d#10]
Is it possible to export the 3D representation of the reconstructed tree skeleton to some 3D format, ideally wavefront .obj-files?
Or are there external tools/packages for converting MTG to OBJ?

Best
Hannah

**Comment by fredboudon** [comment]
You can but it is a bit buggy. For this you need to have reconstructed a 3D representation (that you will be able to export). Then you need to deactivate all other view (MTG, control points, radius, etc) in the View menu as they are not exportable. And you can go to File > Export View > As PlantGL file. You should select in file type selection 'All Files (*.*)' and give an OBJ name. This should export the 3D mesh of the 3D representation in the obj format. 
I will try to make a simpler export in future version.
Cheers,

Fred

**Comment by fredboudon** [comment]
New version is available (v1.2.2) which contains a more direct export to obj : File > Export 3D View > As 3D file format. Now you can directly select obj file in file type selection.
Cheers,

Fred
