### ISSUE TITLE
Angle estimation

### ISSUE THREAD

**Issue by andrianamanousidaki** [openalea/plantscan3d#9]
Hello, I am using plantscan3D to skeletonize arabidopsis. I would like after skeletonization to measure branch angle. Could you provide a tutorial on Angle estimation?
Here is what I tried:
1)I do skeletonization based on the doc files you provide, then 
2) I select angle estimation but 
3) I get an error when I try to save an angles.txt file.

Here is a printscreen with the error.
![error (2)](https://user-images.githubusercontent.com/75805788/114374273-76a34580-9b51-11eb-8cd7-14f42682d099.png)

Thank you !

**Comment by fredboudon** [comment]
Fix in https://github.com/fredboudon/plantscan3d/commit/6133578d92849dd8ae410d8adef5da16370d8c0d. Should be solved in release 1.2.2.
Thanks for your feedback
